(require 'org-sidebar)
(setq org-log-done-with-time 1)
(setq org-log-done 'time)
(require 'ox-md)
(setq org-image-actual-width (/ (display-pixel-width) 3))
(define-key org-mode-map "\M-q" 'toggle-truncate-lines)
